name: Test e2e vAccel

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: [self-hosted]
    outputs:
      vaccelrt_sha: ${{ steps.vars.outputs.vaccelrt_sha }}
      firecracker_sha: ${{ steps.vars.outputs.firecracker_sha }}
      virtio_accel_sha: ${{ steps.vars.outputs.virtio_accel_sha }}
      vsock_plugin_sha: ${{ steps.vars.outputs.vsock_plugin_sha }}
      virtio_plugin_sha: ${{ steps.vars.outputs.virtio_plugin_sha }}
      jetson_plugin_sha: ${{ steps.vars.outputs.jetson_plugin_sha }}
      agent_sha: ${{ steps.vars.outputs.agent_sha }}

    steps:
    - name: Cleanup previous runs
      run: |
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*

    - uses: actions/checkout@v2

    - name: Setup vars
      id: vars
      run: |
        echo "::set-output name=vaccelrt_sha::$(git ls-tree ${{ github.sha }} | grep vaccelrt | awk '{print $3}')"
        echo "::set-output name=firecracker_sha::$(git ls-tree ${{ github.sha }} | grep firecracker | awk '{print $3}')"
        echo "::set-output name=virtio_accel_sha::$(git ls-tree ${{ github.sha }} | grep virtio-accel | awk '{print $3}')"
        echo "::set-output name=vsock_plugin_sha::$(git ls-tree ${{ github.sha }} plugins/vaccelrt-plugin-vsock | awk '{print $3}')"
        echo "::set-output name=virtio_plugin_sha::$(git ls-tree ${{ github.sha }} plugins/vaccelrt-plugin-virtio | awk '{print $3}')"
        echo "::set-output name=jetson_plugin_sha::$(git ls-tree ${{ github.sha }} plugins/vaccelrt-plugin-jetson | awk '{print $3}')"
        echo "::set-output name=agent_sha::$(git ls-tree ${{ github.sha }} agent | awk '{print $3}')"

  test:
    needs: prepare
    runs-on: [self-hosted, "${{ matrix.arch }}" ]
    env:
      NBFC_S3_ACCESS: ${{ secrets.AWS_ACCESS_KEY }}
      NBFC_S3_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VACCELRT_SHA: ${{needs.prepare.outputs.vaccelrt_sha}}
      FIRECRACKER_SHA: ${{ needs.prepare.outputs.firecracker_sha }}
      FIRECRACKER_TYPE: ${{ needs.prepare.outputs.firecracker_build_type }}
      VIRTIO_SHA: ${{ needs.prepare.outputs.virtio_accel_sha }}
      VIRTIO_PLUGIN_SHA: ${{ needs.prepare.outputs.virtio_plugin_sha }}
      VSOCK_PLUGIN_SHA: ${{ needs.prepare.outputs.vsock_plugin_sha }}
      JOB_TYPE: ${{ matrix.build_type }}
      ARCH: ${{ matrix.arch }}

    strategy:
      matrix:
        build_type: [Debug, Release]
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update && sudo apt install -y \
          subversion coreutils rsync iproute2 libfdt-dev

    - name: Setup vars
      id: vars
      run: |
        echo "::set-output name=firecracker_build_type::$(echo ${{ matrix.build_type }} | awk '{print tolower($0)}')"
        echo "::set-output name=uid::$(id -u)"
        echo "::set-output name=gid::$(id -g)"

    - name: Fetch vaccelrt
      uses: cloudkernels/minio-download@v2
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        local-path: /github/workspace/artifacts/opt/
        remote-path: nbfc-assets/github/vaccelrt/${{env.VACCELRT_SHA}}/${{env.ARCH}}/${{ env.JOB_TYPE }}/opt/
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}


    - name: Fetch Firecracker
      uses: cloudkernels/minio-download@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        remote-path: nbfc-assets/github/firecracker/${{ env.FIRECRACKER_SHA }}/${{env.ARCH}}/${{ steps.vars.outputs.firecracker_build_type }}/firecracker
        local-path: /github/workspace/artifacts/opt/bin/
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}

    - name: Fetch vmlinux
      uses: cloudkernels/minio-download@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        remote-path: nbfc-assets/github/virtio-accel/${{ env.VIRTIO_SHA }}/${{env.ARCH}}/linux/vmlinux
        local-path: /github/workspace/artifacts/opt/share/
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}

    - name: Fetch virtio module
      uses: cloudkernels/minio-download@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        remote-path: nbfc-assets/github/virtio-accel/${{ env.VIRTIO_SHA }}/${{env.ARCH}}/linux/virtio_accel.ko
        local-path: /github/workspace/artifacts/opt/share/
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}

    - name: Fetch virtio-plugin
      uses: cloudkernels/minio-download@v2
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        local-path: /github/workspace/artifacts/opt/lib/
        remote-path: nbfc-assets/github/virtio-plugin/${{env.VIRTIO_PLUGIN_SHA}}/${{env.ARCH}}/${{ env.JOB_TYPE }}/libvaccel-virtio.so
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}

    - name: Fetch vsock-plugin
      uses: cloudkernels/minio-download@v2
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        local-path: /github/workspace/artifacts/opt/lib/
        remote-path: nbfc-assets/github/vsock-plugin/${{env.VSOCK_PLUGIN_SHA}}/${{env.ARCH}}/${{ env.JOB_TYPE }}/libvaccel-vsock.so
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}


    - name: Create rootfs
      run: |
        # We need this because downloading from s3 messes up with
        # file permissions
        chmod u+x ${{ github.workspace }}/artifacts/opt/bin/*
        ./scripts/build_rootfs.sh \
                --build_dir /tmp/rootfs_build \
                --install_prefix ${{ github.workspace }}/artifacts/opt \
                --base_image "ubuntu:latest" \
                --dockerfiles_path "$(pwd)/dockerfiles"

    - name: Create tap interface
      run: sudo ./scripts/create_tap.sh tapTestFc 172.42.0.1/24

    - name: Launch Firecracker
      working-directory: ${{ github.workspace }}/artifacts/opt
      run: |
        sudo rm -f fc.sock
        sudo VACCEL_BACKENDS=${{ github.workspace }}/artifacts/opt/lib/libvaccel-noop.so \
          LD_LIBRARY_PATH=${{ github.workspace }}/artifacts/opt/lib:/usr/local/lib:/usr/lib \
          VACCEL_DEBUG_LEVEL=4 \
          ./bin/firecracker \
            --api-sock fc.sock \
            --config-file ${{ github.workspace }}/conf/config_vaccel.json \
            --seccomp-level 0 &

    - name: Test Firecracker is up
      run: ping -c 20 172.42.0.2

    - name: Test Firecracker ssh
      timeout-minutes: 2
      shell: bash {0}
      run: |
        while true
        do
          name=$(ssh -o StrictHostKeyChecking=no -i artifacts/opt/share/fc_test root@172.42.0.2 hostname -s)
          if [[ $name == "vaccel-guest" ]]; then exit 0; fi
        done
        exit 1

    - name: Test virtio-accel
      run: ./scripts/test_virtio.sh -i ${{ github.workspace }}/artifacts/opt/share/fc_test

    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: cloudkernels/vaccelrt-agent
        ref: ${{ needs.prepare.outputs.agent_sha }}
        token: ${{ secrets.NBFC_BUILDER_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
        path: vaccelrt-agent

    - name: Cargo hack
      run: |
        sudo chmod a+w /opt/cargo -R

    - name: Build and install agent
      working-directory: ${{ github.workspace }}/vaccelrt-agent
      env:
        PKG_CONFIG_PATH: ${{ github.workspace }}/artifacts/opt/share/
      run: |
        sudo cp -r ${{ github.workspace }}/artifacts/opt/include/* /usr/include/
        sudo cp ${{ github.workspace }}/artifacts/opt/lib/* /usr/lib/
        cargo install --path .

    - name: Test vsock plugin
      run: |
        sudo ./scripts/test_vsock.sh -i ${{ github.workspace }}/artifacts/opt/share/fc_test -p ${{ github.workspace }}/artifacts/opt/lib/libvaccel-noop.so

    - name: Pack latest release
      if: ${{ github.event_name == 'push' }}
      working-directory: ${{ github.workspace }}/artifacts/opt
      run: |
        cp ${{github.workspace}}/conf/{config_virtio_accel.json,config_vsock.json} share/
        cp /opt/cargo/bin/vaccelrt-agent bin/
        zip -r ${{github.workspace}}/vaccel_${{matrix.arch}}_${{matrix.build_type}}.zip bin/ include/ lib/ \
          share/config_virtio_accel.json share/config_vsock.json \
          share/fc_test share/fc_test.pub \
          share/rootfs.img share/virtio_accel.ko share/vmlinux \
          share/vaccel.pc

    - name: Upload latest master release to s3
      if: ${{ github.event_name == 'push' }}
      uses: cloudkernels/minio-upload@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        remote-path: nbfc-assets/github/vaccel/master/${{env.ARCH}}/${{env.JOB_TYPE}}/
        local-path: /github/workspace/vaccel_${{matrix.arch}}_${{matrix.build_type}}.zip

    - name: Cleanup run
      if: ${{ always() }}
      run: |
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*
        sudo rm -f /tmp/vaccel.sock*
        fc_pid=$(ps aux | grep -m 1 [f]irecracker | awk '{print $2}')
        while true
        do
          fc_pid=$(ps aux | grep -m 1 [f]irecracker | awk '{print $2}')
          if [[ $fc_pid == "" ]]; then break; fi
          echo "Killing Firecracker (pid: $fc_pid)"
          sudo kill -9 $fc_pid
          # Wait for it to actually die
          sleep 2
        done
        sudo ip tuntap del tapTestFc mode tap

  update_latest_release:
    needs: test
    runs-on: [self-hosted]
    env:
      NBFC_S3_ACCESS: ${{ secrets.AWS_ACCESS_KEY }}
      NBFC_S3_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

    - name: Setup vars
      id: vars
      run: |
        echo "::set-output name=uid::$(id -u)"
        echo "::set-output name=gid::$(id -g)"

    - name: Download artifacts
      if: ${{ github.event_name == 'push' }}
      uses: cloudkernels/minio-download@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        remote-path: nbfc-assets/github/vaccel/master/
        local-path: /github/workspace/master/
      env:
        ACTION_UID: ${{ steps.vars.outputs.uid }}
        ACTION_GID: ${{ steps.vars.outputs.gid }}

    - name: Update the release
      if: ${{ github.event_name == 'push' }}
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest master build"
        files: |
          master/vaccel_x86_64_Debug.zip
          master/vaccel_x86_64_Release.zip
          master/vaccel_aarch64_Debug.zip
          master/vaccel_aarch64_Release.zip
